# Generated by Django 4.1.1 on 2022-09-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metering_code', models.CharField(max_length=30)),
                ('timestamp_utc', models.CharField(max_length=30)),
            ],
        ),
    ]
